name: dungeon_improve

services:
  dungeon-escape:
    build:
      context: ..
      dockerfile: infrastructure/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - dungeon_data:/app/data

volumes:
  dungeon_data:
